#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh shell
#       is not compliant, you need to specify some other shell.
#   (2) This script targets any POSIX system that has /bin/sh as the default shell.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1, use it as a starting point.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support.  $var _must_ be set to either true or false.
case $( uname ) in                #(
  Darwin* )     darwin=true ;;    #(
  CYGWIN* )     cygwin=true ;;    #(
  MSYS* | MINGW* ) msys=true ;;   #(
  Linux* )      linux=true ;;     #(
esac

# Determine the command interpreter to use.
# N.B. 'readlink' is not available in all POSIX environments.
case $( uname -s ) in
  Darwin* )
    readlink=/bin/readlink
    ;;
  Linux* )
    readlink=/bin/readlink
    ;;
  CYGWIN* | MINGW* | MSYS* )
    readlink=/bin/readlink
    ;;
  * )
    # Fallback to 'type -p' if readlink is not available
    readlink=$( type -p readlink 2>/dev/null ) || {
      # shellcheck disable=SC2034
      readlink=:
    }
    ;;
esac

# Normalize the path of the shell.
# We need to support MSYS, whose shell is a Windows path.
case $( uname -s ) in
  MSYS* )
    # Normalize the path to a Windows-style path.
    SHELL=$( $readlink -f "$0" )
    ;;
  * )
    SHELL=/bin/sh
    ;;
esac

# Escape application args
save () {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
    echo " "
}

# Collect all arguments for the java command, following the shell quoting and substitution rules
eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
        awk '{ for (i=1; i<=NF; i++) { if (i==1) { printf " \"$%d\"", i } else { printf " \"$%d\"", i } } }' |
        sed "s/^ *//;s/ *$//"
    )"'

exec "$SHELL" "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" "$@"